#ifndef PRINTER_H
#define PRINTER_H

#define PRINTER_MAX_CHARS_ON_LINE   32

#define PRINTER_PRINT(c)			\
  uart0TransmitByte(c)

#define ASCII_PRINTER_ESC        0x1B

#define PRINTER_PAPER_STATUS			\
  PRINTER_PRINT(ASCII_PRINTER_ESC); PRINTER_PRINT('v'); PRINTER_PRINT(0)
#define PRINTER_PRINT_FEED(N)			\
  PRINTER_PRINT(ASCII_PRINTER_ESC); PRINTER_PRINT('d'); PRINTER_PRINT(N)
#define PRINTER_EMPHASIZE_OFF 0
#define PRINTER_EMPHASIZE_ON  1
#define PRINTER_EMPHASIZE(N)			\
  PRINTER_PRINT(ASCII_PRINTER_ESC); PRINTER_PRINT('E'); PRINTER_PRINT(N)
#define PRINTER_REVERSE_OFF 0
#define PRINTER_REVERSE_ON  1
#define PRINTER_REVERSE(N)			\
  PRINTER_PRINT(ASCII_PRINTER_ESC); PRINTER_PRINT('B'); PRINTER_PRINT(N)
#define PRINTER_INITIALIZE			\
  PRINTER_PRINT(ASCII_PRINTER_ESC); PRINTER_PRINT('@')
#define PRINTER_UNDERLINE_OFF 0
#define PRINTER_UNDERLINE_ON1 1
#define PRINTER_UNDERLINE_ON2 2
#define PRINTER_UNDERLINE(N)			\
  PRINTER_PRINT(ASCII_PRINTER_ESC); PRINTER_PRINT('-'); PRINTER_PRINT(N)
#define PRINTER_RX_TIMEOUT			\
  PRINTER_PRINT(0x28); PRINTER_PRINT('t'); PRINTER_PRINT(100)
#define PRINTER_WAKE				\
  PRINTER_PRINT(0xFF); _delay_ms(60)
#define PRINTER_PRINT_TEST_PAGE			\
  PRINTER_PRINT(0x18); PRINTER_PRINT('T')
#define PRINTER_SLEEP_SET(N)			\
  PRINTER_PRINT(ASCII_PRINTER_ESC); PRINTER_PRINT('8'); PRINTER_PRINT(N); PRINTER_PRINT(0)
#define PRINTER_JLEFT   0
#define PRINTER_JCENTER 1
#define PRINTER_JRIGHT  2
#define PRINTER_JUSTIFY(N)			\
  PRINTER_PRINT(ASCII_PRINTER_ESC); PRINTER_PRINT('a'); \
  PRINTER_PRINT(N)
#define PRINTER_LINESPACE_DEFAULT			\
  PRINTER_PRINT(ASCII_PRINTER_ESC); PRINTER_PRINT('2')
#define PRINTER_LINESPACE(N)				\
  PRINTER_PRINT(ASCII_PRINTER_ESC); PRINTER_PRINT('3'); PRINTER_PRINT('0'+N)
#define PRINTER_MODE_SEL(A)				\
  PRINTER_PRINT(ASCII_PRINTER_ESC); PRINTER_PRINT('!'); PRINTER_PRINT(A)
#define PRINTER_MODE_CHARA (0<<0)

#define PRINTER_TOGGLE_ONOFF			\
  PRINTER_PRINT(ASCII_PRINTER_ESC); PRINTER_PRINT('=')
#define PRINTER_ONLINE				\
  PRINTER_TOGGLE_ONOFF;				\
  PRINTER_CMD_ARG(1)
#define PRINTER_OFFLINE				\
  PRINTER_TOGGLE_ONOFF;				\
  PRINTER_CMD_ARG(0)

#define PRINTER_STATUS_ONLINE            (1<<0)
#define PRINTER_STATUS_PAPEROUT          (1<<2)
#define PRINTER_STATUS_VHIGH             (1<<3)
#define PRINTER_STATUS_THIGH             (1<<6)
#define PRINTER_STATUS_UNCONNECTED       (1<<7)

#define PRINTER_CHAR_FONTA               (0<<0)
#define PRINTER_CHAR_FONTB               (1<<0)
#define PRINTER_CHAR_REVERSE_OFF         (0<<1)
#define PRINTER_CHAR_REVERSE_ON          (1<<1)
#define PRINTER_CHAR_EMPHASIZE_OFF       (0<<3)
#define PRINTER_CHAR_EMPHASIZE_ON        (1<<3)

void PRINTER_FONT_ENLARGE(uint8_t N);
void PRINTER_CHARSET(uint8_t N);
void PRINTER_PSTR(const char *P);

#define PRINTER_PRINT_D menuPrnD
#define PRINTER_PRINT_F menuPrnF

#define PRINTER_SPRINTF(STR, FMT, ...)	do {		\
    uint8_t ui8_1t, ui8_2t;				\
    ui8_2t = sprintf_P((char *)STR, FMT, __VA_ARGS__);	\
    for (ui8_1t=0; ui8_1t<ui8_2t; ui8_1t++) {		\
      PRINTER_PRINT(STR[ui8_1t]);			\
    }							\
  } while (0)

#define PRINTER_PRINTN(STR, N)				\
  for (uint8_t _ui8_1=0; _ui8_1<N; _ui8_1++) {		\
    PRINTER_PRINT(STR[_ui8_1]);				\
  }

void printerInit(void);
void printerDefineUserChar(uint8_t idx);
uint8_t printerStatus(void);

#endif
